### ISSUE TITLE
phantomjs-prebuilt

### ISSUE THREAD

**Issue by Sjonnie2nd** [thomasdondorf/phantomjs-pool#1]
Hi Thomas, 

In stead of "phantomjs" or "phantomjs2" i got installed "phantomjs-prebuilt".

In its README.md it says: "Pre-2.0, this package was published to NPM as [phantomjs](https://www.npmjs.com/package/phantomjs). We changed the name to [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) at the request of PhantomJS team."

As a workarround I now use: 
phantomjsBinary: require('phantomjs-prebuilt').path,

Is it an idea to add in /master/Pool.js something like:
try { phantomjsLib = require('phantomjs-prebuilt'); } catch (e) {}

**Comment by thomasdondorf** [comment]
Thank you for opening an issue. I just released a fix (v0.3.2).
