### ISSUE TITLE
Misleading error report in WorkerControl.js

### ISSUE THREAD

**Issue by hoang-tranviet** [thomasdondorf/phantomjs-pool#4]
Hi Thomas,

At first, I have to say this library is so neat and so useful for me.

To be on-topic, in WorkerControl.js script, you try to catch JsonParse error on several lines of code.

However, it is common to have JsonParser success, but  jobCallback(null, result.data)  returns an error. I have crawl error several times (specifically " Crawl Error: Operation canceled for example.com"), due to phantomjs. In this case, the _catch_ reports a misleading jsonParseError, for which I spend a lot of time to debug :))

``` node
                try {
                    log(that.id, 'received result: ' + body);
                    // parse results and pass them to our callback
                    var result = JSON.parse(body);
                    if (result.status === 'success') {
                        jobCallback(null, result.data);
                    } else if (result.status === 'fail') {
                        jobCallback(createError(that.id, result.errMessage), result.data);
                    } else {
                        jobCallback(createError(that.id, 'Communication error between Master and Worker'));
                        result.closing = true;
                        that.createProcess();
                    }
                    that.currentJob = null;

                    // check if phatomjs instance will close down
                    // if the worker signals he is closing, then we just wait for its closing
                    // otherwise we get a job for the worker
                    if (!result.closing) {
                        that.readyForWork();
                    }
                } catch (jsonParseError) {
                    // if that happens, we are in trouble
                    jobCallback(createError(that.id, 'JSON.parse error (content: ' + body + ')'));
                    that.createProcess();
                }
```

And several kind of errors could happen in this block, I guess.

Should we change it to something like below?

``` node
               catch (error) {
                    // if that happens, we are in trouble
                    jobCallback(createError(that.id, ' error: ' + error));
                    // jobCallback(createError(that.id, 'JSON.parse error (content: ' + body + ')'));
                    that.createProcess();
                }

```

Thanks,
Hoang

**Comment by thomasdondorf** [comment]
Hi Hoang,

glad you like the library and sorry for the late answer.

You are right, this is definitely a bug.

There are two ways to fix this as I see it:
- Option 1: As you described: Just catch all errors => Would make it nearly impossible to crash the script
- Option 2: Only wrap the try{} around the `JSON.parse(body)` (this was what I originally intended) => User is still responsible for own bugs in the `jobCallback` function, the script might actually crash, but it would be easier to catch bugs during development

I guess I would prefer option 2 as this would still allow the user to add his own try/catch in the jobCallback function. What do you think?

Do you want to make a fix and pull request?

**Comment by hoang-tranviet** [comment]
Hi Thomas,
Thank you for your kind response.
I will try to submit a fix using method 2 this weekend when I find spare time :)

**Comment by thomasdondorf** [comment]
Awesome! Finally another contributor, welcome on board ;)

**Comment by thomasdondorf** [comment]
Thank you :) #5 solved the issue.
