### ISSUE TITLE
[issue with phantom 1.9.7] 

### ISSUE THREAD

**Issue by iamsahil1989** [thomasdondorf/phantomjs-pool#6]
Below is what we are getting in logs (verbose mode enabled)"403 Directory Listing Denied" with phantom 1.9.7, but things are working fine on phantom **2.1.1**.
```
#1 received result: {"status":"success","closing":true}HTTP/1.1 403 Directory Listing Denied
Content-Type: text/plain
Content-Length: 60
Connection: close

Error 403: Directory Listing Denied
Directory listing denied
    #1 killing worker
    #2  starting on port: 1635
    #2 new job {"noData":true}
    #1 process closed
```
phantomjs-pool doesn't support phantomjs 1.9.7 ?

**Comment by thomasdondorf** [comment]
Sorry for the late answer. It looks like this is a bug with PhantomJS itself (or with the integrated Mongoose server) as others already have figured out: https://github.com/baudehlo/node-phantom-simple/issues/109

In general, the library supports PhantomJS versions < 2, but of course a bug in PhantomJS itself also leads to problems with this library.
